name: ci pipeline
on: [push]
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - run: echo "tiggerd"
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    
        
    
